language: php

php:
    - 5.3
    - 5.4

env:
    - SYMFONY_VERSION=origin/master

before_script:
    - sh -c "psql -c 'create database test;' -U postgres;"
    - mongo test --eval 'db.addUser("travis", "test");'
    - wget http://getcomposer.org/composer.phar
    - php composer.phar install --dev
    - php vendor/vendors.php install
    - pecl install mongo
    - echo "extension=mongo.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`

script: phpunit

notifications:
  email: travis-ci@generation-multiple.com
